// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         hash: "hash"
 *     }
 */
export interface GetTransactionsRequest {
    hash: string;
    raw?: string;
}
