// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { AccountsClient } from "../resources/accounts/client/Client.js";
import { NetworkClient } from "../resources/network/client/Client.js";
import { TokensClient } from "../resources/tokens/client/Client.js";
import { TransactionsClient } from "../resources/transactions/client/Client.js";
import { WalletsClient } from "../resources/wallets/client/Client.js";

export declare namespace EthereumSepoliaClient {
    export type Options = BaseClientOptions;
}

export class EthereumSepoliaClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<EthereumSepoliaClient.Options>;
    protected _wallets: WalletsClient | undefined;
    protected _accounts: AccountsClient | undefined;
    protected _tokens: TokensClient | undefined;
    protected _transactions: TransactionsClient | undefined;
    protected _network: NetworkClient | undefined;

    constructor(options: EthereumSepoliaClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get wallets(): WalletsClient {
        return (this._wallets ??= new WalletsClient(this._options));
    }

    public get accounts(): AccountsClient {
        return (this._accounts ??= new AccountsClient(this._options));
    }

    public get tokens(): TokensClient {
        return (this._tokens ??= new TokensClient(this._options));
    }

    public get transactions(): TransactionsClient {
        return (this._transactions ??= new TransactionsClient(this._options));
    }

    public get network(): NetworkClient {
        return (this._network ??= new NetworkClient(this._options));
    }
}
