// This file was auto-generated by Fern from our API Definition.

import type * as Mainly from "../../../../../index.js";

export type SolanaAccountsGetSolanaDevnetResponse =
    | {
          address: string;
          exists: boolean;
      }
    | {
          address: string;
          exists: boolean;
          lamports: number;
          sol: number;
          owner: string;
          executable: boolean;
          space: number;
          data: Mainly.solanaDevnet.SolanaAccountsGetSolanaDevnetResponseDataData;
      };
