// This file was auto-generated by Fern from our API Definition.

import type * as Mainly from "../../../../../index.js";

export interface SolanaAccountsBatchSolanaDevnetResponse {
    items: SolanaAccountsBatchSolanaDevnetResponse.Items.Item[];
}

export namespace SolanaAccountsBatchSolanaDevnetResponse {
    export type Items = Items.Item[];

    export namespace Items {
        export type Item =
            | {
                  address: string;
                  exists: boolean;
              }
            | {
                  address: string;
                  exists: boolean;
                  lamports: number;
                  sol: number;
                  owner: string;
                  executable: boolean;
                  space: number;
                  data: Mainly.solanaDevnet.SolanaAccountsBatchSolanaDevnetResponseItemsItemDataData;
              };
    }
}
