// This file was auto-generated by Fern from our API Definition.

import * as MainlyTypes from "../../../src/api/index";
import { Mainly } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("CollectionsClient", () => {
    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            address: "address",
            name: "name",
            symbol: "symbol",
            description: "description",
            image: "image",
            itemCount: 1,
            floorPrice: 1.1,
        };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/collections/address")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.solanaDevnet.collections.get({
            address: "address",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/collections/address")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.collections.get({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/collections/address")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.collections.get({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.UnauthorizedError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/collections/address")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.collections.get({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.NotFoundError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/collections/address")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.collections.get({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.ConflictError);
    });

    test("get (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/collections/address")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.collections.get({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.UnprocessableEntityError);
    });

    test("get (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/collections/address")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.collections.get({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.TooManyRequestsError);
    });

    test("get (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/collections/address")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.collections.get({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.InternalServerError);
    });

    test("get (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/collections/address")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.collections.get({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.ServiceUnavailableError);
    });

    test("listNfts (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            address: "address",
            items: [{ id: "id", name: "name", image: "image", standard: "standard", compressed: true, owner: "owner" }],
            nextCursor: "nextCursor",
        };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/collections/address/nfts")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.solanaDevnet.collections.listNfts({
            address: "address",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listNfts (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/collections/address/nfts")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.collections.listNfts({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.BadRequestError);
    });

    test("listNfts (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/collections/address/nfts")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.collections.listNfts({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.UnauthorizedError);
    });

    test("listNfts (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/collections/address/nfts")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.collections.listNfts({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.NotFoundError);
    });

    test("listNfts (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/collections/address/nfts")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.collections.listNfts({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.ConflictError);
    });

    test("listNfts (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/collections/address/nfts")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.collections.listNfts({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.UnprocessableEntityError);
    });

    test("listNfts (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/collections/address/nfts")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.collections.listNfts({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.TooManyRequestsError);
    });

    test("listNfts (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/collections/address/nfts")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.collections.listNfts({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.InternalServerError);
    });

    test("listNfts (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/collections/address/nfts")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.collections.listNfts({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.ServiceUnavailableError);
    });
});
