// This file was auto-generated by Fern from our API Definition.

import * as MainlyTypes from "../../../src/api/index";
import { Mainly } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("NetworkClient", () => {
    test("getStatus (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            health: "ok",
            slot: 1,
            blockHeight: 1,
            epoch: { epoch: 1, slotIndex: 1, slotsInEpoch: 1, progress: 1.1 },
            solanaVersion: "solanaVersion",
        };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/network/status")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.solanaDevnet.network.getStatus();
        expect(response).toEqual(rawResponseBody);
    });

    test("getStatus (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/network/status")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.network.getStatus();
        }).rejects.toThrow(MainlyTypes.BadRequestError);
    });

    test("getStatus (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/network/status")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.network.getStatus();
        }).rejects.toThrow(MainlyTypes.UnauthorizedError);
    });

    test("getStatus (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/network/status")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.network.getStatus();
        }).rejects.toThrow(MainlyTypes.NotFoundError);
    });

    test("getStatus (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/network/status")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.network.getStatus();
        }).rejects.toThrow(MainlyTypes.ConflictError);
    });

    test("getStatus (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/network/status")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.network.getStatus();
        }).rejects.toThrow(MainlyTypes.UnprocessableEntityError);
    });

    test("getStatus (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/network/status")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.network.getStatus();
        }).rejects.toThrow(MainlyTypes.TooManyRequestsError);
    });

    test("getStatus (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/network/status")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.network.getStatus();
        }).rejects.toThrow(MainlyTypes.InternalServerError);
    });

    test("getStatus (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/network/status")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.network.getStatus();
        }).rejects.toThrow(MainlyTypes.ServiceUnavailableError);
    });

    test("getBlockhash (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { blockhash: "blockhash", lastValidBlockHeight: 1, expiresInSeconds: 1 };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/network/blockhash")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.solanaDevnet.network.getBlockhash();
        expect(response).toEqual(rawResponseBody);
    });

    test("getBlockhash (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/network/blockhash")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.network.getBlockhash();
        }).rejects.toThrow(MainlyTypes.BadRequestError);
    });

    test("getBlockhash (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/network/blockhash")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.network.getBlockhash();
        }).rejects.toThrow(MainlyTypes.UnauthorizedError);
    });

    test("getBlockhash (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/network/blockhash")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.network.getBlockhash();
        }).rejects.toThrow(MainlyTypes.NotFoundError);
    });

    test("getBlockhash (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/network/blockhash")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.network.getBlockhash();
        }).rejects.toThrow(MainlyTypes.ConflictError);
    });

    test("getBlockhash (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/network/blockhash")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.network.getBlockhash();
        }).rejects.toThrow(MainlyTypes.UnprocessableEntityError);
    });

    test("getBlockhash (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/network/blockhash")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.network.getBlockhash();
        }).rejects.toThrow(MainlyTypes.TooManyRequestsError);
    });

    test("getBlockhash (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/network/blockhash")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.network.getBlockhash();
        }).rejects.toThrow(MainlyTypes.InternalServerError);
    });

    test("getBlockhash (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/network/blockhash")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.network.getBlockhash();
        }).rejects.toThrow(MainlyTypes.ServiceUnavailableError);
    });

    test("getFees (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            baseFee: { lamportsPerSignature: 1 },
            priority: {
                unit: "microLamportsPerComputeUnit",
                recommended: 1,
                levels: { low: 1, medium: 1, high: 1, veryHigh: 1 },
            },
            updatedAt: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/network/fees")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.solanaDevnet.network.getFees();
        expect(response).toEqual(rawResponseBody);
    });

    test("getFees (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/network/fees")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.network.getFees();
        }).rejects.toThrow(MainlyTypes.BadRequestError);
    });

    test("getFees (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/network/fees")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.network.getFees();
        }).rejects.toThrow(MainlyTypes.UnauthorizedError);
    });

    test("getFees (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/network/fees")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.network.getFees();
        }).rejects.toThrow(MainlyTypes.NotFoundError);
    });

    test("getFees (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/network/fees")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.network.getFees();
        }).rejects.toThrow(MainlyTypes.ConflictError);
    });

    test("getFees (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/network/fees")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.network.getFees();
        }).rejects.toThrow(MainlyTypes.UnprocessableEntityError);
    });

    test("getFees (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/network/fees")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.network.getFees();
        }).rejects.toThrow(MainlyTypes.TooManyRequestsError);
    });

    test("getFees (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/network/fees")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.network.getFees();
        }).rejects.toThrow(MainlyTypes.InternalServerError);
    });

    test("getFees (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/network/fees")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.network.getFees();
        }).rejects.toThrow(MainlyTypes.ServiceUnavailableError);
    });

    test("estimateFees (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = {
            priority: {
                unit: "microLamportsPerComputeUnit",
                recommended: 1,
                levels: { low: 1, medium: 1, high: 1, veryHigh: 1 },
            },
        };

        server
            .mockEndpoint()
            .post("/v1/solana-devnet/network/fees/estimate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.solanaDevnet.network.estimateFees({
            transaction: "transaction",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("estimateFees (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana-devnet/network/fees/estimate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.network.estimateFees({
                transaction: "transaction",
            });
        }).rejects.toThrow(MainlyTypes.BadRequestError);
    });

    test("estimateFees (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana-devnet/network/fees/estimate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.network.estimateFees({
                transaction: "transaction",
            });
        }).rejects.toThrow(MainlyTypes.UnauthorizedError);
    });

    test("estimateFees (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana-devnet/network/fees/estimate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.network.estimateFees({
                transaction: "transaction",
            });
        }).rejects.toThrow(MainlyTypes.NotFoundError);
    });

    test("estimateFees (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana-devnet/network/fees/estimate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.network.estimateFees({
                transaction: "transaction",
            });
        }).rejects.toThrow(MainlyTypes.ConflictError);
    });

    test("estimateFees (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana-devnet/network/fees/estimate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.network.estimateFees({
                transaction: "transaction",
            });
        }).rejects.toThrow(MainlyTypes.UnprocessableEntityError);
    });

    test("estimateFees (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana-devnet/network/fees/estimate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.network.estimateFees({
                transaction: "transaction",
            });
        }).rejects.toThrow(MainlyTypes.TooManyRequestsError);
    });

    test("estimateFees (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana-devnet/network/fees/estimate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.network.estimateFees({
                transaction: "transaction",
            });
        }).rejects.toThrow(MainlyTypes.InternalServerError);
    });

    test("estimateFees (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana-devnet/network/fees/estimate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.network.estimateFees({
                transaction: "transaction",
            });
        }).rejects.toThrow(MainlyTypes.ServiceUnavailableError);
    });
});
