// This file was auto-generated by Fern from our API Definition.

import * as MainlyTypes from "../../../src/api/index";
import { Mainly } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("WalletsClient", () => {
    test("getBalance (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { address: "address", lamports: 1, sol: 1.1 };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/balance")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.solanaDevnet.wallets.getBalance({
            address: "address",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getBalance (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/balance")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.wallets.getBalance({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.BadRequestError);
    });

    test("getBalance (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/balance")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.wallets.getBalance({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.UnauthorizedError);
    });

    test("getBalance (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/balance")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.wallets.getBalance({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.NotFoundError);
    });

    test("getBalance (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/balance")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.wallets.getBalance({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.ConflictError);
    });

    test("getBalance (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/balance")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.wallets.getBalance({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.UnprocessableEntityError);
    });

    test("getBalance (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/balance")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.wallets.getBalance({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.TooManyRequestsError);
    });

    test("getBalance (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/balance")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.wallets.getBalance({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.InternalServerError);
    });

    test("getBalance (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/balance")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.wallets.getBalance({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.ServiceUnavailableError);
    });

    test("listTokens (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            address: "address",
            native: { lamports: 1, sol: 1.1, price: 1.1 },
            items: [
                {
                    mint: "mint",
                    name: "name",
                    symbol: "symbol",
                    logo: "logo",
                    tokenProgram: "tokenProgram",
                    balance: { raw: "raw", decimals: 1, ui: 1.1, uiString: "uiString" },
                    price: 1.1,
                },
            ],
            nextCursor: "nextCursor",
        };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/tokens")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.solanaDevnet.wallets.listTokens({
            address: "address",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listTokens (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/tokens")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.wallets.listTokens({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.BadRequestError);
    });

    test("listTokens (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/tokens")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.wallets.listTokens({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.UnauthorizedError);
    });

    test("listTokens (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/tokens")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.wallets.listTokens({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.NotFoundError);
    });

    test("listTokens (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/tokens")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.wallets.listTokens({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.ConflictError);
    });

    test("listTokens (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/tokens")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.wallets.listTokens({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.UnprocessableEntityError);
    });

    test("listTokens (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/tokens")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.wallets.listTokens({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.TooManyRequestsError);
    });

    test("listTokens (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/tokens")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.wallets.listTokens({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.InternalServerError);
    });

    test("listTokens (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/tokens")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.wallets.listTokens({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.ServiceUnavailableError);
    });

    test("listNfts (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            address: "address",
            items: [
                {
                    id: "id",
                    name: "name",
                    image: "image",
                    standard: "standard",
                    compressed: true,
                    collection: { address: "address", name: null, verified: true },
                },
            ],
            nextCursor: "nextCursor",
        };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/nfts")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.solanaDevnet.wallets.listNfts({
            address: "address",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listNfts (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/nfts")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.wallets.listNfts({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.BadRequestError);
    });

    test("listNfts (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/nfts")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.wallets.listNfts({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.UnauthorizedError);
    });

    test("listNfts (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/nfts")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.wallets.listNfts({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.NotFoundError);
    });

    test("listNfts (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/nfts")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.wallets.listNfts({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.ConflictError);
    });

    test("listNfts (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/nfts")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.wallets.listNfts({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.UnprocessableEntityError);
    });

    test("listNfts (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/nfts")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.wallets.listNfts({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.TooManyRequestsError);
    });

    test("listNfts (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/nfts")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.wallets.listNfts({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.InternalServerError);
    });

    test("listNfts (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/nfts")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.wallets.listNfts({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.ServiceUnavailableError);
    });

    test("listTransactions (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            address: "address",
            items: [
                {
                    signature: "signature",
                    timestamp: "timestamp",
                    slot: 1,
                    status: "success",
                    type: "transfer",
                    source: "source",
                    description: "description",
                    fee: { lamports: 1, sol: 1.1 },
                    transfers: {
                        sol: [{ from: "from", to: "to", lamports: 1, sol: 1.1 }],
                        tokens: [
                            {
                                mint: null,
                                symbol: null,
                                from: "from",
                                to: "to",
                                amount: { raw: "raw", decimals: 1, ui: 1.1, uiString: "uiString" },
                            },
                        ],
                    },
                },
            ],
            nextCursor: "nextCursor",
        };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/transactions")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.solanaDevnet.wallets.listTransactions({
            address: "address",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listTransactions (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/transactions")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.wallets.listTransactions({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.BadRequestError);
    });

    test("listTransactions (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/transactions")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.wallets.listTransactions({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.UnauthorizedError);
    });

    test("listTransactions (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/transactions")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.wallets.listTransactions({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.NotFoundError);
    });

    test("listTransactions (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/transactions")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.wallets.listTransactions({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.ConflictError);
    });

    test("listTransactions (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/transactions")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.wallets.listTransactions({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.UnprocessableEntityError);
    });

    test("listTransactions (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/transactions")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.wallets.listTransactions({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.TooManyRequestsError);
    });

    test("listTransactions (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/transactions")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.wallets.listTransactions({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.InternalServerError);
    });

    test("listTransactions (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana-devnet/wallets/address/transactions")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solanaDevnet.wallets.listTransactions({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.ServiceUnavailableError);
    });
});
