// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         address: "address"
 *     }
 */
export interface ListNftsWalletsRequest {
    address: string;
    limit?: number;
    cursor?: string;
    collection?: string;
    includeAttributes?: string;
}
