// This file was auto-generated by Fern from our API Definition.

import type * as Mainly from "../../../../../../index.js";

/**
 * @example
 *     {
 *         address: "address"
 *     }
 */
export interface ListTransactionsWalletsRequest {
    address: string;
    limit?: number;
    cursor?: string;
    type?: Mainly.solana.ListTransactionsWalletsRequestType;
    confirmation?: Mainly.solana.ListTransactionsWalletsRequestConfirmation;
}
