// This file was auto-generated by Fern from our API Definition.

export interface SolanaWalletsListTokensSolanaDevnetResponse {
    address: string;
    native: SolanaWalletsListTokensSolanaDevnetResponse.Native;
    items: SolanaWalletsListTokensSolanaDevnetResponse.Items.Item[];
    nextCursor: string | null;
}

export namespace SolanaWalletsListTokensSolanaDevnetResponse {
    export interface Native {
        lamports: number;
        sol: number;
        price: number | null;
    }

    export type Items = Items.Item[];

    export namespace Items {
        export interface Item {
            mint: string;
            name: string | null;
            symbol: string | null;
            logo: string | null;
            tokenProgram: string;
            balance: Item.Balance;
            price: number | null;
        }

        export namespace Item {
            export interface Balance {
                raw: string;
                decimals: number;
                ui: number;
                uiString: string;
            }
        }
    }
}
