// This file was auto-generated by Fern from our API Definition.

export interface SolanaWalletsListTransactionsSolanaDevnetResponse {
    address: string;
    items: SolanaWalletsListTransactionsSolanaDevnetResponse.Items.Item[];
    nextCursor: string | null;
}

export namespace SolanaWalletsListTransactionsSolanaDevnetResponse {
    export type Items = Items.Item[];

    export namespace Items {
        export interface Item {
            signature: string;
            timestamp: string | null;
            slot: number;
            status: Item.Status;
            type: Item.Type;
            source: string | null;
            description: string;
            fee: Item.Fee;
            transfers: Item.Transfers;
        }

        export namespace Item {
            export const Status = {
                Success: "success",
                Failed: "failed",
            } as const;
            export type Status = (typeof Status)[keyof typeof Status];
            export const Type = {
                Transfer: "transfer",
                Swap: "swap",
                NftSale: "nftSale",
                NftMint: "nftMint",
                Stake: "stake",
                Burn: "burn",
                Other: "other",
            } as const;
            export type Type = (typeof Type)[keyof typeof Type];

            export interface Fee {
                lamports: number;
                sol: number;
            }

            export interface Transfers {
                sol: Transfers.Sol.Item[];
                tokens: Transfers.Tokens.Item[];
            }

            export namespace Transfers {
                export type Sol = Sol.Item[];

                export namespace Sol {
                    export interface Item {
                        from: string;
                        to: string;
                        lamports: number;
                        sol: number;
                    }
                }

                export type Tokens = Tokens.Item[];

                export namespace Tokens {
                    export interface Item {
                        mint: string | null;
                        symbol: string | null;
                        from: string;
                        to: string;
                        amount: Item.Amount;
                    }

                    export namespace Item {
                        export interface Amount {
                            raw: string;
                            decimals: number;
                            ui: number;
                            uiString: string;
                        }
                    }
                }
            }
        }
    }
}
