// This file was auto-generated by Fern from our API Definition.

export interface SolanaTransactionsSendSolanaDevnetResponse {
    signature: string;
    status: SolanaTransactionsSendSolanaDevnetResponse.Status;
    slot?: number | undefined;
    fee?: SolanaTransactionsSendSolanaDevnetResponse.Fee | undefined;
}

export namespace SolanaTransactionsSendSolanaDevnetResponse {
    export const Status = {
        Submitted: "submitted",
        Confirmed: "confirmed",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];

    export interface Fee {
        lamports: number;
        sol: number;
    }
}
