// This file was auto-generated by Fern from our API Definition.

export interface SolanaTransactionsSimulateSolanaDevnetResponse {
    success: boolean;
    computeUnits: number;
    logs: string[];
    error: SolanaTransactionsSimulateSolanaDevnetResponse.Error_ | null;
}

export namespace SolanaTransactionsSimulateSolanaDevnetResponse {
    export interface Error_ {
        code: string;
        message: string;
        programErrorCode: string | null;
    }
}
