// This file was auto-generated by Fern from our API Definition.

export interface SolanaTransactionsGetStatusSolanaDevnetResponse {
    signature: string;
    status: SolanaTransactionsGetStatusSolanaDevnetResponse.Status;
    slot: number | null;
    error?: unknown | undefined;
}

export namespace SolanaTransactionsGetStatusSolanaDevnetResponse {
    export const Status = {
        Submitted: "submitted",
        Confirmed: "confirmed",
        Finalized: "finalized",
        Failed: "failed",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
