// This file was auto-generated by Fern from our API Definition.

export interface SolanaTransactionsGetSolanaDevnetResponse {
    signature: string;
    timestamp: string | null;
    slot: number;
    status: SolanaTransactionsGetSolanaDevnetResponse.Status;
    type: SolanaTransactionsGetSolanaDevnetResponse.Type;
    source: string | null;
    description: string;
    fee: SolanaTransactionsGetSolanaDevnetResponse.Fee;
    transfers: SolanaTransactionsGetSolanaDevnetResponse.Transfers;
    confirmation: SolanaTransactionsGetSolanaDevnetResponse.Confirmation;
    signers: string[];
    logs: string[];
    raw?: unknown | undefined;
}

export namespace SolanaTransactionsGetSolanaDevnetResponse {
    export const Status = {
        Success: "success",
        Failed: "failed",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    export const Type = {
        Transfer: "transfer",
        Swap: "swap",
        NftSale: "nftSale",
        NftMint: "nftMint",
        Stake: "stake",
        Burn: "burn",
        Other: "other",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];

    export interface Fee {
        lamports: number;
        sol: number;
    }

    export interface Transfers {
        sol: Transfers.Sol.Item[];
        tokens: Transfers.Tokens.Item[];
    }

    export namespace Transfers {
        export type Sol = Sol.Item[];

        export namespace Sol {
            export interface Item {
                from: string;
                to: string;
                lamports: number;
                sol: number;
            }
        }

        export type Tokens = Tokens.Item[];

        export namespace Tokens {
            export interface Item {
                mint: string | null;
                symbol: string | null;
                from: string;
                to: string;
                amount: Item.Amount;
            }

            export namespace Item {
                export interface Amount {
                    raw: string;
                    decimals: number;
                    ui: number;
                    uiString: string;
                }
            }
        }
    }

    export const Confirmation = {
        Confirmed: "confirmed",
        Finalized: "finalized",
    } as const;
    export type Confirmation = (typeof Confirmation)[keyof typeof Confirmation];
}
