// This file was auto-generated by Fern from our API Definition.

export interface SolanaCollectionsGetSolanaDevnetResponse {
    address: string;
    name: string | null;
    symbol: string | null;
    description: string | null;
    image: string | null;
    itemCount: number;
    floorPrice: number | null;
}
