// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         addresses: ["addresses"]
 *     }
 */
export interface SolanaAccountsBatchSolanaDevnetRequest {
    addresses: string[];
    confirmation?: SolanaAccountsBatchSolanaDevnetRequest.Confirmation;
}

export namespace SolanaAccountsBatchSolanaDevnetRequest {
    export const Confirmation = {
        Processed: "processed",
        Confirmed: "confirmed",
        Finalized: "finalized",
    } as const;
    export type Confirmation = (typeof Confirmation)[keyof typeof Confirmation];
}
