// This file was auto-generated by Fern from our API Definition.

export interface SolanaTokensListHoldersSolanaDevnetResponse {
    mint: string;
    supply: SolanaTokensListHoldersSolanaDevnetResponse.Supply;
    items: SolanaTokensListHoldersSolanaDevnetResponse.Items.Item[];
}

export namespace SolanaTokensListHoldersSolanaDevnetResponse {
    export interface Supply {
        raw: string;
        ui: number;
        uiString: string;
    }

    export type Items = Items.Item[];

    export namespace Items {
        export interface Item {
            owner: string;
            balance: Item.Balance;
            percentOfSupply: number;
        }

        export namespace Item {
            export interface Balance {
                raw: string;
                decimals: number;
                ui: number;
                uiString: string;
            }
        }
    }
}
