// This file was auto-generated by Fern from our API Definition.

export interface SolanaTokensGetSolanaDevnetResponse {
    mint: string;
    name: string | null;
    symbol: string | null;
    logo: string | null;
    decimals: number;
    tokenProgram: SolanaTokensGetSolanaDevnetResponse.TokenProgram;
    supply: SolanaTokensGetSolanaDevnetResponse.Supply;
    price: number | null;
    authorities: SolanaTokensGetSolanaDevnetResponse.Authorities;
}

export namespace SolanaTokensGetSolanaDevnetResponse {
    export const TokenProgram = {
        SplToken: "spl-token",
        Token2022: "token-2022",
    } as const;
    export type TokenProgram = (typeof TokenProgram)[keyof typeof TokenProgram];

    export interface Supply {
        raw: string;
        ui: number;
        uiString: string;
    }

    export interface Authorities {
        mint: string | null;
        freeze: string | null;
    }
}
