// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         programId: "programId"
 *     }
 */
export interface ListAccountsProgramsRequest {
    programId: string;
    size?: number;
    match?: string | string[];
    limit?: number;
    cursor?: string;
}
