// This file was auto-generated by Fern from our API Definition.

import * as MainlyTypes from "../../../src/api/index";
import { Mainly } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("AccountsClient", () => {
    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { address: "address", exists: true };

        server
            .mockEndpoint()
            .get("/v1/solana/accounts/address")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.solana.accounts.get({
            address: "address",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/accounts/address")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.accounts.get({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/accounts/address")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.accounts.get({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.UnauthorizedError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/accounts/address")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.accounts.get({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.NotFoundError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/accounts/address")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.accounts.get({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.ConflictError);
    });

    test("get (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/accounts/address")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.accounts.get({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.UnprocessableEntityError);
    });

    test("get (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/accounts/address")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.accounts.get({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.TooManyRequestsError);
    });

    test("get (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/accounts/address")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.accounts.get({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.InternalServerError);
    });

    test("get (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/accounts/address")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.accounts.get({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.ServiceUnavailableError);
    });

    test("batch (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { addresses: ["addresses"] };
        const rawResponseBody = { items: [{ address: "address", exists: true }] };

        server
            .mockEndpoint()
            .post("/v1/solana/accounts/batch")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.solana.accounts.batch({
            addresses: ["addresses"],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("batch (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { addresses: ["addresses", "addresses"] };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana/accounts/batch")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.accounts.batch({
                addresses: ["addresses", "addresses"],
            });
        }).rejects.toThrow(MainlyTypes.BadRequestError);
    });

    test("batch (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { addresses: ["addresses", "addresses"] };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana/accounts/batch")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.accounts.batch({
                addresses: ["addresses", "addresses"],
            });
        }).rejects.toThrow(MainlyTypes.UnauthorizedError);
    });

    test("batch (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { addresses: ["addresses", "addresses"] };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana/accounts/batch")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.accounts.batch({
                addresses: ["addresses", "addresses"],
            });
        }).rejects.toThrow(MainlyTypes.NotFoundError);
    });

    test("batch (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { addresses: ["addresses", "addresses"] };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana/accounts/batch")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.accounts.batch({
                addresses: ["addresses", "addresses"],
            });
        }).rejects.toThrow(MainlyTypes.ConflictError);
    });

    test("batch (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { addresses: ["addresses", "addresses"] };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana/accounts/batch")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.accounts.batch({
                addresses: ["addresses", "addresses"],
            });
        }).rejects.toThrow(MainlyTypes.UnprocessableEntityError);
    });

    test("batch (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { addresses: ["addresses", "addresses"] };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana/accounts/batch")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.accounts.batch({
                addresses: ["addresses", "addresses"],
            });
        }).rejects.toThrow(MainlyTypes.TooManyRequestsError);
    });

    test("batch (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { addresses: ["addresses", "addresses"] };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana/accounts/batch")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.accounts.batch({
                addresses: ["addresses", "addresses"],
            });
        }).rejects.toThrow(MainlyTypes.InternalServerError);
    });

    test("batch (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { addresses: ["addresses", "addresses"] };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana/accounts/batch")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.accounts.batch({
                addresses: ["addresses", "addresses"],
            });
        }).rejects.toThrow(MainlyTypes.ServiceUnavailableError);
    });
});
