// This file was auto-generated by Fern from our API Definition.

import * as MainlyTypes from "../../../src/api/index";
import { Mainly } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("NftsClient", () => {
    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            name: "name",
            image: "image",
            standard: "standard",
            compressed: true,
            collection: { address: "address", name: "name", verified: true },
            symbol: "symbol",
            description: "description",
            externalUrl: "externalUrl",
            mutable: true,
            burnt: true,
            owner: { address: "address", delegated: true, frozen: true },
            attributes: [{ traitType: "traitType", value: { key: "value" } }],
            royalties: { percent: 1.1, primarySaleHappened: true, recipients: [{ address: "address", share: 1.1 }] },
        };

        server.mockEndpoint().get("/v1/solana/nfts/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.solana.nfts.get({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server.mockEndpoint().get("/v1/solana/nfts/id").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.solana.nfts.get({
                id: "id",
            });
        }).rejects.toThrow(MainlyTypes.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server.mockEndpoint().get("/v1/solana/nfts/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.solana.nfts.get({
                id: "id",
            });
        }).rejects.toThrow(MainlyTypes.UnauthorizedError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server.mockEndpoint().get("/v1/solana/nfts/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.solana.nfts.get({
                id: "id",
            });
        }).rejects.toThrow(MainlyTypes.NotFoundError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server.mockEndpoint().get("/v1/solana/nfts/id").respondWith().statusCode(409).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.solana.nfts.get({
                id: "id",
            });
        }).rejects.toThrow(MainlyTypes.ConflictError);
    });

    test("get (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server.mockEndpoint().get("/v1/solana/nfts/id").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.solana.nfts.get({
                id: "id",
            });
        }).rejects.toThrow(MainlyTypes.UnprocessableEntityError);
    });

    test("get (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server.mockEndpoint().get("/v1/solana/nfts/id").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.solana.nfts.get({
                id: "id",
            });
        }).rejects.toThrow(MainlyTypes.TooManyRequestsError);
    });

    test("get (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server.mockEndpoint().get("/v1/solana/nfts/id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.solana.nfts.get({
                id: "id",
            });
        }).rejects.toThrow(MainlyTypes.InternalServerError);
    });

    test("get (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server.mockEndpoint().get("/v1/solana/nfts/id").respondWith().statusCode(503).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.solana.nfts.get({
                id: "id",
            });
        }).rejects.toThrow(MainlyTypes.ServiceUnavailableError);
    });
});
