// This file was auto-generated by Fern from our API Definition.

import * as MainlyTypes from "../../../src/api/index";
import { Mainly } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("ProgramsClient", () => {
    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            programId: "programId",
            name: "name",
            executable: true,
            loader: "upgradeable",
            upgradeAuthority: "upgradeAuthority",
            lastDeployedSlot: 1,
            sizeBytes: 1,
        };

        server
            .mockEndpoint()
            .get("/v1/solana/programs/programId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.solana.programs.get({
            programId: "programId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/programs/programId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.programs.get({
                programId: "programId",
            });
        }).rejects.toThrow(MainlyTypes.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/programs/programId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.programs.get({
                programId: "programId",
            });
        }).rejects.toThrow(MainlyTypes.UnauthorizedError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/programs/programId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.programs.get({
                programId: "programId",
            });
        }).rejects.toThrow(MainlyTypes.NotFoundError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/programs/programId")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.programs.get({
                programId: "programId",
            });
        }).rejects.toThrow(MainlyTypes.ConflictError);
    });

    test("get (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/programs/programId")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.programs.get({
                programId: "programId",
            });
        }).rejects.toThrow(MainlyTypes.UnprocessableEntityError);
    });

    test("get (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/programs/programId")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.programs.get({
                programId: "programId",
            });
        }).rejects.toThrow(MainlyTypes.TooManyRequestsError);
    });

    test("get (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/programs/programId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.programs.get({
                programId: "programId",
            });
        }).rejects.toThrow(MainlyTypes.InternalServerError);
    });

    test("get (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/programs/programId")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.programs.get({
                programId: "programId",
            });
        }).rejects.toThrow(MainlyTypes.ServiceUnavailableError);
    });

    test("listAccounts (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            programId: "programId",
            items: [
                {
                    address: "address",
                    lamports: 1,
                    sol: 1.1,
                    space: 1,
                    data: { format: "base64", base64: "base64", program: null },
                },
            ],
            nextCursor: "nextCursor",
        };

        server
            .mockEndpoint()
            .get("/v1/solana/programs/programId/accounts")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.solana.programs.listAccounts({
            programId: "programId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listAccounts (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/programs/programId/accounts")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.programs.listAccounts({
                programId: "programId",
            });
        }).rejects.toThrow(MainlyTypes.BadRequestError);
    });

    test("listAccounts (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/programs/programId/accounts")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.programs.listAccounts({
                programId: "programId",
            });
        }).rejects.toThrow(MainlyTypes.UnauthorizedError);
    });

    test("listAccounts (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/programs/programId/accounts")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.programs.listAccounts({
                programId: "programId",
            });
        }).rejects.toThrow(MainlyTypes.NotFoundError);
    });

    test("listAccounts (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/programs/programId/accounts")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.programs.listAccounts({
                programId: "programId",
            });
        }).rejects.toThrow(MainlyTypes.ConflictError);
    });

    test("listAccounts (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/programs/programId/accounts")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.programs.listAccounts({
                programId: "programId",
            });
        }).rejects.toThrow(MainlyTypes.UnprocessableEntityError);
    });

    test("listAccounts (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/programs/programId/accounts")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.programs.listAccounts({
                programId: "programId",
            });
        }).rejects.toThrow(MainlyTypes.TooManyRequestsError);
    });

    test("listAccounts (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/programs/programId/accounts")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.programs.listAccounts({
                programId: "programId",
            });
        }).rejects.toThrow(MainlyTypes.InternalServerError);
    });

    test("listAccounts (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/programs/programId/accounts")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.programs.listAccounts({
                programId: "programId",
            });
        }).rejects.toThrow(MainlyTypes.ServiceUnavailableError);
    });

    test("view (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { data: "data", accounts: [{ address: "address" }] };
        const rawResponseBody = {
            success: true,
            returnData: { base64: "base64", programId: "programId" },
            computeUnits: 1,
            logs: ["logs"],
        };

        server
            .mockEndpoint()
            .post("/v1/solana/programs/programId/view")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.solana.programs.view({
            programId: "programId",
            data: "data",
            accounts: [
                {
                    address: "address",
                },
            ],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("view (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { data: "data", accounts: [{ address: "address" }, { address: "address" }] };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana/programs/programId/view")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.programs.view({
                programId: "programId",
                data: "data",
                accounts: [
                    {
                        address: "address",
                    },
                    {
                        address: "address",
                    },
                ],
            });
        }).rejects.toThrow(MainlyTypes.BadRequestError);
    });

    test("view (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { data: "data", accounts: [{ address: "address" }, { address: "address" }] };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana/programs/programId/view")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.programs.view({
                programId: "programId",
                data: "data",
                accounts: [
                    {
                        address: "address",
                    },
                    {
                        address: "address",
                    },
                ],
            });
        }).rejects.toThrow(MainlyTypes.UnauthorizedError);
    });

    test("view (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { data: "data", accounts: [{ address: "address" }, { address: "address" }] };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana/programs/programId/view")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.programs.view({
                programId: "programId",
                data: "data",
                accounts: [
                    {
                        address: "address",
                    },
                    {
                        address: "address",
                    },
                ],
            });
        }).rejects.toThrow(MainlyTypes.NotFoundError);
    });

    test("view (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { data: "data", accounts: [{ address: "address" }, { address: "address" }] };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana/programs/programId/view")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.programs.view({
                programId: "programId",
                data: "data",
                accounts: [
                    {
                        address: "address",
                    },
                    {
                        address: "address",
                    },
                ],
            });
        }).rejects.toThrow(MainlyTypes.ConflictError);
    });

    test("view (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { data: "data", accounts: [{ address: "address" }, { address: "address" }] };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana/programs/programId/view")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.programs.view({
                programId: "programId",
                data: "data",
                accounts: [
                    {
                        address: "address",
                    },
                    {
                        address: "address",
                    },
                ],
            });
        }).rejects.toThrow(MainlyTypes.UnprocessableEntityError);
    });

    test("view (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { data: "data", accounts: [{ address: "address" }, { address: "address" }] };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana/programs/programId/view")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.programs.view({
                programId: "programId",
                data: "data",
                accounts: [
                    {
                        address: "address",
                    },
                    {
                        address: "address",
                    },
                ],
            });
        }).rejects.toThrow(MainlyTypes.TooManyRequestsError);
    });

    test("view (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { data: "data", accounts: [{ address: "address" }, { address: "address" }] };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana/programs/programId/view")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.programs.view({
                programId: "programId",
                data: "data",
                accounts: [
                    {
                        address: "address",
                    },
                    {
                        address: "address",
                    },
                ],
            });
        }).rejects.toThrow(MainlyTypes.InternalServerError);
    });

    test("view (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { data: "data", accounts: [{ address: "address" }, { address: "address" }] };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana/programs/programId/view")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.programs.view({
                programId: "programId",
                data: "data",
                accounts: [
                    {
                        address: "address",
                    },
                    {
                        address: "address",
                    },
                ],
            });
        }).rejects.toThrow(MainlyTypes.ServiceUnavailableError);
    });
});
