// This file was auto-generated by Fern from our API Definition.

import * as MainlyTypes from "../../../src/api/index";
import { Mainly } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("TransactionsClient", () => {
    test("getStatus (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { signature: "signature", status: "submitted", slot: 1, error: { key: "value" } };

        server
            .mockEndpoint()
            .get("/v1/solana/transactions/signature/status")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.solana.transactions.getStatus({
            signature: "signature",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getStatus (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/transactions/signature/status")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.transactions.getStatus({
                signature: "signature",
            });
        }).rejects.toThrow(MainlyTypes.BadRequestError);
    });

    test("getStatus (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/transactions/signature/status")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.transactions.getStatus({
                signature: "signature",
            });
        }).rejects.toThrow(MainlyTypes.UnauthorizedError);
    });

    test("getStatus (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/transactions/signature/status")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.transactions.getStatus({
                signature: "signature",
            });
        }).rejects.toThrow(MainlyTypes.NotFoundError);
    });

    test("getStatus (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/transactions/signature/status")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.transactions.getStatus({
                signature: "signature",
            });
        }).rejects.toThrow(MainlyTypes.ConflictError);
    });

    test("getStatus (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/transactions/signature/status")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.transactions.getStatus({
                signature: "signature",
            });
        }).rejects.toThrow(MainlyTypes.UnprocessableEntityError);
    });

    test("getStatus (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/transactions/signature/status")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.transactions.getStatus({
                signature: "signature",
            });
        }).rejects.toThrow(MainlyTypes.TooManyRequestsError);
    });

    test("getStatus (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/transactions/signature/status")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.transactions.getStatus({
                signature: "signature",
            });
        }).rejects.toThrow(MainlyTypes.InternalServerError);
    });

    test("getStatus (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/transactions/signature/status")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.transactions.getStatus({
                signature: "signature",
            });
        }).rejects.toThrow(MainlyTypes.ServiceUnavailableError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            signature: "signature",
            timestamp: "timestamp",
            slot: 1,
            status: "success",
            type: "transfer",
            source: "source",
            description: "description",
            fee: { lamports: 1, sol: 1.1 },
            transfers: {
                sol: [{ from: "from", to: "to", lamports: 1, sol: 1.1 }],
                tokens: [
                    {
                        mint: null,
                        symbol: null,
                        from: "from",
                        to: "to",
                        amount: { raw: "raw", decimals: 1, ui: 1.1, uiString: "uiString" },
                    },
                ],
            },
            confirmation: "confirmed",
            signers: ["signers"],
            logs: ["logs"],
            raw: { key: "value" },
        };

        server
            .mockEndpoint()
            .get("/v1/solana/transactions/signature")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.solana.transactions.get({
            signature: "signature",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/transactions/signature")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.transactions.get({
                signature: "signature",
            });
        }).rejects.toThrow(MainlyTypes.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/transactions/signature")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.transactions.get({
                signature: "signature",
            });
        }).rejects.toThrow(MainlyTypes.UnauthorizedError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/transactions/signature")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.transactions.get({
                signature: "signature",
            });
        }).rejects.toThrow(MainlyTypes.NotFoundError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/transactions/signature")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.transactions.get({
                signature: "signature",
            });
        }).rejects.toThrow(MainlyTypes.ConflictError);
    });

    test("get (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/transactions/signature")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.transactions.get({
                signature: "signature",
            });
        }).rejects.toThrow(MainlyTypes.UnprocessableEntityError);
    });

    test("get (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/transactions/signature")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.transactions.get({
                signature: "signature",
            });
        }).rejects.toThrow(MainlyTypes.TooManyRequestsError);
    });

    test("get (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/transactions/signature")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.transactions.get({
                signature: "signature",
            });
        }).rejects.toThrow(MainlyTypes.InternalServerError);
    });

    test("get (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/solana/transactions/signature")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.transactions.get({
                signature: "signature",
            });
        }).rejects.toThrow(MainlyTypes.ServiceUnavailableError);
    });

    test("simulate (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = {
            success: true,
            computeUnits: 1,
            logs: ["logs"],
            error: { code: "code", message: "message", programErrorCode: "programErrorCode" },
        };

        server
            .mockEndpoint()
            .post("/v1/solana/transactions/simulate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.solana.transactions.simulate({
            transaction: "transaction",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("simulate (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana/transactions/simulate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.transactions.simulate({
                transaction: "transaction",
            });
        }).rejects.toThrow(MainlyTypes.BadRequestError);
    });

    test("simulate (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana/transactions/simulate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.transactions.simulate({
                transaction: "transaction",
            });
        }).rejects.toThrow(MainlyTypes.UnauthorizedError);
    });

    test("simulate (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana/transactions/simulate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.transactions.simulate({
                transaction: "transaction",
            });
        }).rejects.toThrow(MainlyTypes.NotFoundError);
    });

    test("simulate (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana/transactions/simulate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.transactions.simulate({
                transaction: "transaction",
            });
        }).rejects.toThrow(MainlyTypes.ConflictError);
    });

    test("simulate (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana/transactions/simulate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.transactions.simulate({
                transaction: "transaction",
            });
        }).rejects.toThrow(MainlyTypes.UnprocessableEntityError);
    });

    test("simulate (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana/transactions/simulate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.transactions.simulate({
                transaction: "transaction",
            });
        }).rejects.toThrow(MainlyTypes.TooManyRequestsError);
    });

    test("simulate (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana/transactions/simulate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.transactions.simulate({
                transaction: "transaction",
            });
        }).rejects.toThrow(MainlyTypes.InternalServerError);
    });

    test("simulate (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana/transactions/simulate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.transactions.simulate({
                transaction: "transaction",
            });
        }).rejects.toThrow(MainlyTypes.ServiceUnavailableError);
    });

    test("send (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = {
            signature: "signature",
            status: "submitted",
            slot: 1,
            fee: { lamports: 1, sol: 1.1 },
        };

        server
            .mockEndpoint()
            .post("/v1/solana/transactions/send")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.solana.transactions.send({
            transaction: "transaction",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("send (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana/transactions/send")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.transactions.send({
                transaction: "transaction",
            });
        }).rejects.toThrow(MainlyTypes.BadRequestError);
    });

    test("send (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana/transactions/send")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.transactions.send({
                transaction: "transaction",
            });
        }).rejects.toThrow(MainlyTypes.UnauthorizedError);
    });

    test("send (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana/transactions/send")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.transactions.send({
                transaction: "transaction",
            });
        }).rejects.toThrow(MainlyTypes.NotFoundError);
    });

    test("send (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana/transactions/send")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.transactions.send({
                transaction: "transaction",
            });
        }).rejects.toThrow(MainlyTypes.ConflictError);
    });

    test("send (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana/transactions/send")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.transactions.send({
                transaction: "transaction",
            });
        }).rejects.toThrow(MainlyTypes.UnprocessableEntityError);
    });

    test("send (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana/transactions/send")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.transactions.send({
                transaction: "transaction",
            });
        }).rejects.toThrow(MainlyTypes.TooManyRequestsError);
    });

    test("send (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana/transactions/send")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.transactions.send({
                transaction: "transaction",
            });
        }).rejects.toThrow(MainlyTypes.InternalServerError);
    });

    test("send (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/solana/transactions/send")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.transactions.send({
                transaction: "transaction",
            });
        }).rejects.toThrow(MainlyTypes.ServiceUnavailableError);
    });
});
