// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         transaction: "transaction"
 *     }
 */
export interface EthereumTransactionsSendEthereumRequest {
    transaction: string;
}
