// This file was auto-generated by Fern from our API Definition.

import type * as Mainly from "../../../../../../index.js";

/**
 * @example
 *     {
 *         address: "address"
 *     }
 */
export interface GetBalanceWalletsRequest {
    address: string;
    block?: Mainly.ethereum.GetBalanceWalletsRequestBlock;
}
