// This file was auto-generated by Fern from our API Definition.

export interface EthereumTransactionsGetStatusEthereumSepoliaResponse {
    hash: string;
    status: EthereumTransactionsGetStatusEthereumSepoliaResponse.Status;
    blockNumber: number | null;
    error: EthereumTransactionsGetStatusEthereumSepoliaResponse.Error_ | null;
}

export namespace EthereumTransactionsGetStatusEthereumSepoliaResponse {
    export const Status = {
        Submitted: "submitted",
        Confirmed: "confirmed",
        Failed: "failed",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];

    export interface Error_ {
        code: string;
        message: string;
    }
}
