// This file was auto-generated by Fern from our API Definition.

export interface EthereumTransactionsSimulateEthereumSepoliaResponse {
    success: boolean;
    returnData: string | null;
    gasEstimate: string | null;
    error: EthereumTransactionsSimulateEthereumSepoliaResponse.Error_ | null;
}

export namespace EthereumTransactionsSimulateEthereumSepoliaResponse {
    export interface Error_ {
        code: string;
        message: string;
        details?: unknown | undefined;
    }
}
