// This file was auto-generated by Fern from our API Definition.

export interface EthereumTransactionsSendEthereumSepoliaResponse {
    hash: string;
    status: EthereumTransactionsSendEthereumSepoliaResponse.Status;
}

export namespace EthereumTransactionsSendEthereumSepoliaResponse {
    export const Status = {
        Submitted: "submitted",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
