// This file was auto-generated by Fern from our API Definition.

export interface EthereumAccountsGetEthereumResponse {
    address: string;
    type: EthereumAccountsGetEthereumResponse.Type;
    balance: EthereumAccountsGetEthereumResponse.Balance;
    nonce: number;
    code: EthereumAccountsGetEthereumResponse.Code;
}

export namespace EthereumAccountsGetEthereumResponse {
    export const Type = {
        ExternallyOwned: "externallyOwned",
        Contract: "contract",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];

    export interface Balance {
        wei: string;
        eth: string;
    }

    export interface Code {
        present: boolean;
        sizeBytes: number;
    }
}
