// This file was auto-generated by Fern from our API Definition.

export const GetAccountsRequestBlock = {
    Earliest: "earliest",
    Latest: "latest",
    Pending: "pending",
    Safe: "safe",
    Finalized: "finalized",
} as const;
export type GetAccountsRequestBlock = (typeof GetAccountsRequestBlock)[keyof typeof GetAccountsRequestBlock];
