// This file was auto-generated by Fern from our API Definition.

export interface SolanaTransactionsSimulateSolanaResponse {
    success: boolean;
    computeUnits: number;
    logs: string[];
    error: SolanaTransactionsSimulateSolanaResponse.Error_ | null;
}

export namespace SolanaTransactionsSimulateSolanaResponse {
    export interface Error_ {
        code: string;
        message: string;
        programErrorCode: string | null;
    }
}
