// This file was auto-generated by Fern from our API Definition.

export interface SolanaTransactionsGetStatusSolanaResponse {
    signature: string;
    status: SolanaTransactionsGetStatusSolanaResponse.Status;
    slot: number | null;
    error?: unknown | undefined;
}

export namespace SolanaTransactionsGetStatusSolanaResponse {
    export const Status = {
        Submitted: "submitted",
        Confirmed: "confirmed",
        Finalized: "finalized",
        Failed: "failed",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
