// This file was auto-generated by Fern from our API Definition.

export interface SolanaTransactionsSendSolanaResponse {
    signature: string;
    status: SolanaTransactionsSendSolanaResponse.Status;
    slot?: number | undefined;
    fee?: SolanaTransactionsSendSolanaResponse.Fee | undefined;
}

export namespace SolanaTransactionsSendSolanaResponse {
    export const Status = {
        Submitted: "submitted",
        Confirmed: "confirmed",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];

    export interface Fee {
        lamports: number;
        sol: number;
    }
}
