// This file was auto-generated by Fern from our API Definition.

export interface EthereumTransactionsGetEthereumResponse {
    hash: string;
    from: string;
    to: string | null;
    blockNumber: number | null;
    blockHash: string | null;
    transactionIndex: number | null;
    nonce: number;
    status: EthereumTransactionsGetEthereumResponse.Status;
    value: EthereumTransactionsGetEthereumResponse.Value;
    gasLimit: string;
    gasUsed: string | null;
    fee: EthereumTransactionsGetEthereumResponse.Fee | null;
    input: string;
    creates: string | null;
    logs: unknown[];
    raw?: EthereumTransactionsGetEthereumResponse.Raw | undefined;
}

export namespace EthereumTransactionsGetEthereumResponse {
    export const Status = {
        Success: "success",
        Failed: "failed",
        Pending: "pending",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];

    export interface Value {
        wei: string;
        eth: string;
    }

    export interface Fee {
        wei: string;
        eth: string;
    }

    export interface Raw {
        transaction?: unknown | undefined;
        receipt?: unknown | undefined;
    }
}
