// This file was auto-generated by Fern from our API Definition.

export interface EthereumTransactionsSendEthereumResponse {
    hash: string;
    status: EthereumTransactionsSendEthereumResponse.Status;
}

export namespace EthereumTransactionsSendEthereumResponse {
    export const Status = {
        Submitted: "submitted",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
