// This file was auto-generated by Fern from our API Definition.

export interface EthereumTransactionsSimulateEthereumResponse {
    success: boolean;
    returnData: string | null;
    gasEstimate: string | null;
    error: EthereumTransactionsSimulateEthereumResponse.Error_ | null;
}

export namespace EthereumTransactionsSimulateEthereumResponse {
    export interface Error_ {
        code: string;
        message: string;
        details?: unknown | undefined;
    }
}
