// This file was auto-generated by Fern from our API Definition.

export const GetAccountsRequestConfirmation = {
    Processed: "processed",
    Confirmed: "confirmed",
    Finalized: "finalized",
} as const;
export type GetAccountsRequestConfirmation =
    (typeof GetAccountsRequestConfirmation)[keyof typeof GetAccountsRequestConfirmation];
