// This file was auto-generated by Fern from our API Definition.

import type * as Mainly from "../../../../../index.js";

export type SolanaAccountsBatchSolanaResponseItemsItemDataData =
    | Mainly.solana.SolanaAccountsBatchSolanaResponseItemsItemDataData.Parsed
    | Mainly.solana.SolanaAccountsBatchSolanaResponseItemsItemDataData.Base64;

export namespace SolanaAccountsBatchSolanaResponseItemsItemDataData {
    export interface Parsed {
        format: "parsed";
        program: string;
        parsed?: unknown | undefined;
    }

    export interface Base64 {
        format: "base64";
        base64: string;
        program: string | null;
    }
}
