// This file was auto-generated by Fern from our API Definition.

import type * as Mainly from "../../../../../index.js";

export interface SolanaAccountsBatchSolanaResponse {
    items: SolanaAccountsBatchSolanaResponse.Items.Item[];
}

export namespace SolanaAccountsBatchSolanaResponse {
    export type Items = Items.Item[];

    export namespace Items {
        export type Item =
            | {
                  address: string;
                  exists: boolean;
              }
            | {
                  address: string;
                  exists: boolean;
                  lamports: number;
                  sol: number;
                  owner: string;
                  executable: boolean;
                  space: number;
                  data: Mainly.solana.SolanaAccountsBatchSolanaResponseItemsItemDataData;
              };
    }
}
