// This file was auto-generated by Fern from our API Definition.

export interface ApiError {
    error: ApiError.Error_;
}

export namespace ApiError {
    export interface Error_ {
        code: string;
        message: string;
        details?: Record<string, unknown> | undefined;
    }
}
