// This file was auto-generated by Fern from our API Definition.

export interface SolanaNftsGetSolanaResponse {
    id: string;
    name: string | null;
    image: string | null;
    standard: SolanaNftsGetSolanaResponse.Standard;
    compressed: boolean;
    collection: SolanaNftsGetSolanaResponse.Collection | null;
    symbol: string | null;
    description: string | null;
    externalUrl: string | null;
    mutable: boolean;
    burnt: boolean;
    owner: SolanaNftsGetSolanaResponse.Owner;
    attributes: SolanaNftsGetSolanaResponse.Attributes.Item[];
    royalties: SolanaNftsGetSolanaResponse.Royalties;
}

export namespace SolanaNftsGetSolanaResponse {
    export const Standard = {
        Standard: "standard",
        Programmable: "programmable",
        Edition: "edition",
    } as const;
    export type Standard = (typeof Standard)[keyof typeof Standard];

    export interface Collection {
        address: string;
        name: string | null;
        verified: boolean;
    }

    export interface Owner {
        address: string | null;
        delegated: boolean;
        frozen: boolean;
    }

    export type Attributes = Attributes.Item[];

    export namespace Attributes {
        export interface Item {
            traitType: string;
            value?: unknown | undefined;
        }
    }

    export interface Royalties {
        percent: number;
        primarySaleHappened: boolean;
        recipients: Royalties.Recipients.Item[];
    }

    export namespace Royalties {
        export type Recipients = Recipients.Item[];

        export namespace Recipients {
            export interface Item {
                address: string;
                share: number;
            }
        }
    }
}
