// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         address: "address"
 *     }
 */
export interface ListTokensWalletsRequest {
    address: string;
    limit?: number;
    cursor?: string;
    includeZeroBalances?: string;
}
