// This file was auto-generated by Fern from our API Definition.

import type * as Mainly from "../../../../../index.js";

export interface SolanaProgramsListAccountsSolanaDevnetResponse {
    programId: string;
    items: SolanaProgramsListAccountsSolanaDevnetResponse.Items.Item[];
    nextCursor: string | null;
}

export namespace SolanaProgramsListAccountsSolanaDevnetResponse {
    export type Items = Items.Item[];

    export namespace Items {
        export interface Item {
            address: string;
            lamports: number;
            sol: number;
            space: number;
            data: Mainly.solanaDevnet.SolanaProgramsListAccountsSolanaDevnetResponseItemsItemData;
        }
    }
}
