// This file was auto-generated by Fern from our API Definition.

export type SolanaProgramsViewSolanaDevnetResponse =
    | {
          success: boolean;
          returnData: {
              base64: string | null;
              programId: string;
          } | null;
          computeUnits: number;
          logs: string[];
      }
    | {
          success: boolean;
          computeUnits: number;
          logs: string[];
          error: {
              code: string;
              message: string;
              programErrorCode: string | null;
          };
      };
