// This file was auto-generated by Fern from our API Definition.

export interface SolanaProgramsGetSolanaDevnetResponse {
    programId: string;
    name: string | null;
    executable: boolean;
    loader: SolanaProgramsGetSolanaDevnetResponse.Loader;
    upgradeAuthority: string | null;
    lastDeployedSlot: number | null;
    sizeBytes: number;
}

export namespace SolanaProgramsGetSolanaDevnetResponse {
    export const Loader = {
        Upgradeable: "upgradeable",
        Legacy: "legacy",
        Native: "native",
    } as const;
    export type Loader = (typeof Loader)[keyof typeof Loader];
}
