// This file was auto-generated by Fern from our API Definition.

export interface EthereumNetworkGetStatusEthereumSepoliaResponse {
    chain: EthereumNetworkGetStatusEthereumSepoliaResponse.Chain;
    chainId: number;
    networkId: string;
    blockNumber: number;
    clientVersion: string;
    syncing: boolean;
}

export namespace EthereumNetworkGetStatusEthereumSepoliaResponse {
    export const Chain = {
        Ethereum: "ethereum",
        EthereumSepolia: "ethereum-sepolia",
    } as const;
    export type Chain = (typeof Chain)[keyof typeof Chain];
}
