// This file was auto-generated by Fern from our API Definition.

export interface EthereumNetworkGetFeesEthereumSepoliaResponse {
    gasPrice: EthereumNetworkGetFeesEthereumSepoliaResponse.GasPrice;
    baseFee: EthereumNetworkGetFeesEthereumSepoliaResponse.BaseFee | null;
    priorityFee: EthereumNetworkGetFeesEthereumSepoliaResponse.PriorityFee | null;
}

export namespace EthereumNetworkGetFeesEthereumSepoliaResponse {
    export interface GasPrice {
        wei: string;
        gwei: string;
    }

    export interface BaseFee {
        wei: string;
        gwei: string;
    }

    export interface PriorityFee {
        low: PriorityFee.Low;
        medium: PriorityFee.Medium;
        high: PriorityFee.High;
    }

    export namespace PriorityFee {
        export interface Low {
            wei: string;
            gwei: string;
        }

        export interface Medium {
            wei: string;
            gwei: string;
        }

        export interface High {
            wei: string;
            gwei: string;
        }
    }
}
