// This file was auto-generated by Fern from our API Definition.

export interface EthereumNetworkGetStatusEthereumResponse {
    chain: EthereumNetworkGetStatusEthereumResponse.Chain;
    chainId: number;
    networkId: string;
    blockNumber: number;
    clientVersion: string;
    syncing: boolean;
}

export namespace EthereumNetworkGetStatusEthereumResponse {
    export const Chain = {
        Ethereum: "ethereum",
        EthereumSepolia: "ethereum-sepolia",
    } as const;
    export type Chain = (typeof Chain)[keyof typeof Chain];
}
