// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { AccountsClient } from "../resources/accounts/client/Client.js";
import { CollectionsClient } from "../resources/collections/client/Client.js";
import { NetworkClient } from "../resources/network/client/Client.js";
import { NftsClient } from "../resources/nfts/client/Client.js";
import { ProgramsClient } from "../resources/programs/client/Client.js";
import { TokensClient } from "../resources/tokens/client/Client.js";
import { TransactionsClient } from "../resources/transactions/client/Client.js";
import { WalletsClient } from "../resources/wallets/client/Client.js";

export declare namespace SolanaDevnetClient {
    export type Options = BaseClientOptions;
}

export class SolanaDevnetClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<SolanaDevnetClient.Options>;
    protected _wallets: WalletsClient | undefined;
    protected _transactions: TransactionsClient | undefined;
    protected _tokens: TokensClient | undefined;
    protected _nfts: NftsClient | undefined;
    protected _collections: CollectionsClient | undefined;
    protected _programs: ProgramsClient | undefined;
    protected _accounts: AccountsClient | undefined;
    protected _network: NetworkClient | undefined;

    constructor(options: SolanaDevnetClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get wallets(): WalletsClient {
        return (this._wallets ??= new WalletsClient(this._options));
    }

    public get transactions(): TransactionsClient {
        return (this._transactions ??= new TransactionsClient(this._options));
    }

    public get tokens(): TokensClient {
        return (this._tokens ??= new TokensClient(this._options));
    }

    public get nfts(): NftsClient {
        return (this._nfts ??= new NftsClient(this._options));
    }

    public get collections(): CollectionsClient {
        return (this._collections ??= new CollectionsClient(this._options));
    }

    public get programs(): ProgramsClient {
        return (this._programs ??= new ProgramsClient(this._options));
    }

    public get accounts(): AccountsClient {
        return (this._accounts ??= new AccountsClient(this._options));
    }

    public get network(): NetworkClient {
        return (this._network ??= new NetworkClient(this._options));
    }
}
