// This file was auto-generated by Fern from our API Definition.

import type * as Mainly from "../../../../../index.js";

export type SolanaProgramsListAccountsSolanaResponseItemsItemData =
    | Mainly.solana.SolanaProgramsListAccountsSolanaResponseItemsItemData.Parsed
    | Mainly.solana.SolanaProgramsListAccountsSolanaResponseItemsItemData.Base64;

export namespace SolanaProgramsListAccountsSolanaResponseItemsItemData {
    export interface Parsed {
        format: "parsed";
        program: string;
        parsed?: unknown | undefined;
    }

    export interface Base64 {
        format: "base64";
        base64: string;
        program: string | null;
    }
}
