// This file was auto-generated by Fern from our API Definition.

import type * as Mainly from "../../../../../index.js";

export interface SolanaProgramsListAccountsSolanaResponse {
    programId: string;
    items: SolanaProgramsListAccountsSolanaResponse.Items.Item[];
    nextCursor: string | null;
}

export namespace SolanaProgramsListAccountsSolanaResponse {
    export type Items = Items.Item[];

    export namespace Items {
        export interface Item {
            address: string;
            lamports: number;
            sol: number;
            space: number;
            data: Mainly.solana.SolanaProgramsListAccountsSolanaResponseItemsItemData;
        }
    }
}
