// This file was auto-generated by Fern from our API Definition.

import * as MainlyTypes from "../../../src/api/index";
import { Mainly } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("TransactionsClient", () => {
    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            hash: "hash",
            from: "from",
            to: "to",
            blockNumber: 1,
            blockHash: "blockHash",
            transactionIndex: 1,
            nonce: 1,
            status: "success",
            value: { wei: "wei", eth: "eth" },
            gasLimit: "gasLimit",
            gasUsed: "gasUsed",
            fee: { wei: "wei", eth: "eth" },
            input: "input",
            creates: "creates",
            logs: [{ key: "value" }],
            raw: { transaction: { key: "value" }, receipt: { key: "value" } },
        };

        server
            .mockEndpoint()
            .get("/v1/ethereum-sepolia/transactions/hash")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.ethereumSepolia.transactions.get({
            hash: "hash",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum-sepolia/transactions/hash")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereumSepolia.transactions.get({
                hash: "hash",
            });
        }).rejects.toThrow(MainlyTypes.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum-sepolia/transactions/hash")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereumSepolia.transactions.get({
                hash: "hash",
            });
        }).rejects.toThrow(MainlyTypes.UnauthorizedError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum-sepolia/transactions/hash")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereumSepolia.transactions.get({
                hash: "hash",
            });
        }).rejects.toThrow(MainlyTypes.NotFoundError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum-sepolia/transactions/hash")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereumSepolia.transactions.get({
                hash: "hash",
            });
        }).rejects.toThrow(MainlyTypes.ConflictError);
    });

    test("get (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum-sepolia/transactions/hash")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereumSepolia.transactions.get({
                hash: "hash",
            });
        }).rejects.toThrow(MainlyTypes.UnprocessableEntityError);
    });

    test("get (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum-sepolia/transactions/hash")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereumSepolia.transactions.get({
                hash: "hash",
            });
        }).rejects.toThrow(MainlyTypes.TooManyRequestsError);
    });

    test("get (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum-sepolia/transactions/hash")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereumSepolia.transactions.get({
                hash: "hash",
            });
        }).rejects.toThrow(MainlyTypes.InternalServerError);
    });

    test("get (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum-sepolia/transactions/hash")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereumSepolia.transactions.get({
                hash: "hash",
            });
        }).rejects.toThrow(MainlyTypes.ServiceUnavailableError);
    });

    test("getStatus (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            hash: "hash",
            status: "submitted",
            blockNumber: 1,
            error: { code: "code", message: "message" },
        };

        server
            .mockEndpoint()
            .get("/v1/ethereum-sepolia/transactions/hash/status")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.ethereumSepolia.transactions.getStatus({
            hash: "hash",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getStatus (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum-sepolia/transactions/hash/status")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereumSepolia.transactions.getStatus({
                hash: "hash",
            });
        }).rejects.toThrow(MainlyTypes.BadRequestError);
    });

    test("getStatus (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum-sepolia/transactions/hash/status")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereumSepolia.transactions.getStatus({
                hash: "hash",
            });
        }).rejects.toThrow(MainlyTypes.UnauthorizedError);
    });

    test("getStatus (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum-sepolia/transactions/hash/status")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereumSepolia.transactions.getStatus({
                hash: "hash",
            });
        }).rejects.toThrow(MainlyTypes.NotFoundError);
    });

    test("getStatus (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum-sepolia/transactions/hash/status")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereumSepolia.transactions.getStatus({
                hash: "hash",
            });
        }).rejects.toThrow(MainlyTypes.ConflictError);
    });

    test("getStatus (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum-sepolia/transactions/hash/status")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereumSepolia.transactions.getStatus({
                hash: "hash",
            });
        }).rejects.toThrow(MainlyTypes.UnprocessableEntityError);
    });

    test("getStatus (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum-sepolia/transactions/hash/status")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereumSepolia.transactions.getStatus({
                hash: "hash",
            });
        }).rejects.toThrow(MainlyTypes.TooManyRequestsError);
    });

    test("getStatus (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum-sepolia/transactions/hash/status")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereumSepolia.transactions.getStatus({
                hash: "hash",
            });
        }).rejects.toThrow(MainlyTypes.InternalServerError);
    });

    test("getStatus (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum-sepolia/transactions/hash/status")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereumSepolia.transactions.getStatus({
                hash: "hash",
            });
        }).rejects.toThrow(MainlyTypes.ServiceUnavailableError);
    });

    test("simulate (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: {} };
        const rawResponseBody = {
            success: true,
            returnData: "returnData",
            gasEstimate: "gasEstimate",
            error: { code: "code", message: "message", details: { key: "value" } },
        };

        server
            .mockEndpoint()
            .post("/v1/ethereum-sepolia/transactions/simulate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.ethereumSepolia.transactions.simulate({
            transaction: {},
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("simulate (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: {} };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/ethereum-sepolia/transactions/simulate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereumSepolia.transactions.simulate({
                transaction: {},
            });
        }).rejects.toThrow(MainlyTypes.BadRequestError);
    });

    test("simulate (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: {} };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/ethereum-sepolia/transactions/simulate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereumSepolia.transactions.simulate({
                transaction: {},
            });
        }).rejects.toThrow(MainlyTypes.UnauthorizedError);
    });

    test("simulate (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: {} };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/ethereum-sepolia/transactions/simulate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereumSepolia.transactions.simulate({
                transaction: {},
            });
        }).rejects.toThrow(MainlyTypes.NotFoundError);
    });

    test("simulate (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: {} };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/ethereum-sepolia/transactions/simulate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereumSepolia.transactions.simulate({
                transaction: {},
            });
        }).rejects.toThrow(MainlyTypes.ConflictError);
    });

    test("simulate (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: {} };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/ethereum-sepolia/transactions/simulate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereumSepolia.transactions.simulate({
                transaction: {},
            });
        }).rejects.toThrow(MainlyTypes.UnprocessableEntityError);
    });

    test("simulate (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: {} };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/ethereum-sepolia/transactions/simulate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereumSepolia.transactions.simulate({
                transaction: {},
            });
        }).rejects.toThrow(MainlyTypes.TooManyRequestsError);
    });

    test("simulate (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: {} };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/ethereum-sepolia/transactions/simulate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereumSepolia.transactions.simulate({
                transaction: {},
            });
        }).rejects.toThrow(MainlyTypes.InternalServerError);
    });

    test("simulate (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: {} };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/ethereum-sepolia/transactions/simulate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereumSepolia.transactions.simulate({
                transaction: {},
            });
        }).rejects.toThrow(MainlyTypes.ServiceUnavailableError);
    });

    test("send (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { hash: "hash", status: "submitted" };

        server
            .mockEndpoint()
            .post("/v1/ethereum-sepolia/transactions/send")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.ethereumSepolia.transactions.send({
            transaction: "transaction",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("send (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/ethereum-sepolia/transactions/send")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereumSepolia.transactions.send({
                transaction: "transaction",
            });
        }).rejects.toThrow(MainlyTypes.BadRequestError);
    });

    test("send (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/ethereum-sepolia/transactions/send")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereumSepolia.transactions.send({
                transaction: "transaction",
            });
        }).rejects.toThrow(MainlyTypes.UnauthorizedError);
    });

    test("send (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/ethereum-sepolia/transactions/send")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereumSepolia.transactions.send({
                transaction: "transaction",
            });
        }).rejects.toThrow(MainlyTypes.NotFoundError);
    });

    test("send (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/ethereum-sepolia/transactions/send")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereumSepolia.transactions.send({
                transaction: "transaction",
            });
        }).rejects.toThrow(MainlyTypes.ConflictError);
    });

    test("send (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/ethereum-sepolia/transactions/send")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereumSepolia.transactions.send({
                transaction: "transaction",
            });
        }).rejects.toThrow(MainlyTypes.UnprocessableEntityError);
    });

    test("send (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/ethereum-sepolia/transactions/send")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereumSepolia.transactions.send({
                transaction: "transaction",
            });
        }).rejects.toThrow(MainlyTypes.TooManyRequestsError);
    });

    test("send (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/ethereum-sepolia/transactions/send")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereumSepolia.transactions.send({
                transaction: "transaction",
            });
        }).rejects.toThrow(MainlyTypes.InternalServerError);
    });

    test("send (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: "transaction" };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/ethereum-sepolia/transactions/send")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereumSepolia.transactions.send({
                transaction: "transaction",
            });
        }).rejects.toThrow(MainlyTypes.ServiceUnavailableError);
    });
});
