// This file was auto-generated by Fern from our API Definition.

export interface SolanaNetworkEstimateFeesSolanaDevnetResponse {
    priority: SolanaNetworkEstimateFeesSolanaDevnetResponse.Priority;
}

export namespace SolanaNetworkEstimateFeesSolanaDevnetResponse {
    export interface Priority {
        unit: Priority.Unit;
        recommended: number;
        levels: Priority.Levels;
    }

    export namespace Priority {
        export const Unit = {
            MicroLamportsPerComputeUnit: "microLamportsPerComputeUnit",
        } as const;
        export type Unit = (typeof Unit)[keyof typeof Unit];

        export interface Levels {
            low: number;
            medium: number;
            high: number;
            veryHigh: number;
        }
    }
}
