// This file was auto-generated by Fern from our API Definition.

export interface SolanaNetworkGetStatusSolanaDevnetResponse {
    health: SolanaNetworkGetStatusSolanaDevnetResponse.Health;
    slot: number;
    blockHeight: number;
    epoch: SolanaNetworkGetStatusSolanaDevnetResponse.Epoch;
    solanaVersion: string;
}

export namespace SolanaNetworkGetStatusSolanaDevnetResponse {
    export const Health = {
        Ok: "ok",
        Degraded: "degraded",
    } as const;
    export type Health = (typeof Health)[keyof typeof Health];

    export interface Epoch {
        epoch: number;
        slotIndex: number;
        slotsInEpoch: number;
        progress: number;
    }
}
