// This file was auto-generated by Fern from our API Definition.

export const GetBalanceWalletsRequestConfirmation = {
    Processed: "processed",
    Confirmed: "confirmed",
    Finalized: "finalized",
} as const;
export type GetBalanceWalletsRequestConfirmation =
    (typeof GetBalanceWalletsRequestConfirmation)[keyof typeof GetBalanceWalletsRequestConfirmation];
