// This file was auto-generated by Fern from our API Definition.

export const ListTransactionsWalletsRequestConfirmation = {
    Processed: "processed",
    Confirmed: "confirmed",
    Finalized: "finalized",
} as const;
export type ListTransactionsWalletsRequestConfirmation =
    (typeof ListTransactionsWalletsRequestConfirmation)[keyof typeof ListTransactionsWalletsRequestConfirmation];
