// This file was auto-generated by Fern from our API Definition.

export const ListTransactionsWalletsRequestType = {
    Transfer: "transfer",
    Swap: "swap",
    NftSale: "nftSale",
    NftMint: "nftMint",
    Stake: "stake",
    Burn: "burn",
    Other: "other",
} as const;
export type ListTransactionsWalletsRequestType =
    (typeof ListTransactionsWalletsRequestType)[keyof typeof ListTransactionsWalletsRequestType];
