// This file was auto-generated by Fern from our API Definition.

export interface SolanaWalletsListNftsSolanaResponse {
    address: string;
    items: SolanaWalletsListNftsSolanaResponse.Items.Item[];
    nextCursor: string | null;
}

export namespace SolanaWalletsListNftsSolanaResponse {
    export type Items = Items.Item[];

    export namespace Items {
        export interface Item {
            id: string;
            name: string | null;
            image: string | null;
            standard: Item.Standard;
            compressed: boolean;
            collection: Item.Collection | null;
            attributes?: Item.Attributes.Item[] | undefined;
        }

        export namespace Item {
            export const Standard = {
                Standard: "standard",
                Programmable: "programmable",
                Edition: "edition",
            } as const;
            export type Standard = (typeof Standard)[keyof typeof Standard];

            export interface Collection {
                address: string;
                name: string | null;
                verified: boolean;
            }

            export type Attributes = Attributes.Item[];

            export namespace Attributes {
                export interface Item {
                    traitType: string;
                    value?: unknown | undefined;
                }
            }
        }
    }
}
