// This file was auto-generated by Fern from our API Definition.

export const GetBalanceWalletsRequestBlock = {
    Earliest: "earliest",
    Latest: "latest",
    Pending: "pending",
    Safe: "safe",
    Finalized: "finalized",
} as const;
export type GetBalanceWalletsRequestBlock =
    (typeof GetBalanceWalletsRequestBlock)[keyof typeof GetBalanceWalletsRequestBlock];
