// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         signature: "signature"
 *     }
 */
export interface GetTransactionsRequest {
    signature: string;
    raw?: string;
}
