// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         transaction: "transaction"
 *     }
 */
export interface SolanaTransactionsSendSolanaRequest {
    transaction: string;
    priorityFee?: SolanaTransactionsSendSolanaRequest.PriorityFee;
    confirm?: boolean;
    skipPreflight?: boolean;
}

export namespace SolanaTransactionsSendSolanaRequest {
    export type PriorityFee = ("auto" | "low" | "medium" | "high") | number;
}
