// This file was auto-generated by Fern from our API Definition.

export interface SolanaCollectionsListNftsSolanaResponse {
    address: string;
    items: SolanaCollectionsListNftsSolanaResponse.Items.Item[];
    nextCursor: string | null;
}

export namespace SolanaCollectionsListNftsSolanaResponse {
    export type Items = Items.Item[];

    export namespace Items {
        export interface Item {
            id: string;
            name: string | null;
            image: string | null;
            standard: Item.Standard;
            compressed: boolean;
            owner: string | null;
        }

        export namespace Item {
            export const Standard = {
                Standard: "standard",
                Programmable: "programmable",
                Edition: "edition",
            } as const;
            export type Standard = (typeof Standard)[keyof typeof Standard];
        }
    }
}
