// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         programId: "programId"
 *     }
 */
export interface GetProgramsRequest {
    programId: string;
}
