// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         programId: "programId",
 *         data: "data",
 *         accounts: [{
 *                 address: "address"
 *             }]
 *     }
 */
export interface SolanaProgramsViewSolanaDevnetRequest {
    programId: string;
    data: string;
    accounts: SolanaProgramsViewSolanaDevnetRequest.Accounts.Item[];
    payer?: string;
}

export namespace SolanaProgramsViewSolanaDevnetRequest {
    export type Accounts = Accounts.Item[];

    export namespace Accounts {
        export interface Item {
            address: string;
            writable?: boolean | undefined;
            signer?: boolean | undefined;
        }
    }
}
