// This file was auto-generated by Fern from our API Definition.

export interface EthereumAccountsBatchEthereumSepoliaResponse {
    items: EthereumAccountsBatchEthereumSepoliaResponse.Items.Item[];
}

export namespace EthereumAccountsBatchEthereumSepoliaResponse {
    export type Items = Items.Item[];

    export namespace Items {
        export interface Item {
            address: string;
            balance: Item.Balance | null;
        }

        export namespace Item {
            export interface Balance {
                wei: string;
                eth: string;
            }
        }
    }
}
