// This file was auto-generated by Fern from our API Definition.

export interface EthereumAccountsGetEthereumSepoliaResponse {
    address: string;
    type: EthereumAccountsGetEthereumSepoliaResponse.Type;
    balance: EthereumAccountsGetEthereumSepoliaResponse.Balance;
    nonce: number;
    code: EthereumAccountsGetEthereumSepoliaResponse.Code;
}

export namespace EthereumAccountsGetEthereumSepoliaResponse {
    export const Type = {
        ExternallyOwned: "externallyOwned",
        Contract: "contract",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];

    export interface Balance {
        wei: string;
        eth: string;
    }

    export interface Code {
        present: boolean;
        sizeBytes: number;
    }
}
