// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         mint: "mint"
 *     }
 */
export interface ListHoldersTokensRequest {
    mint: string;
    limit?: number;
}
