// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         addresses: ["addresses"]
 *     }
 */
export interface SolanaAccountsBatchSolanaRequest {
    addresses: string[];
    confirmation?: SolanaAccountsBatchSolanaRequest.Confirmation;
}

export namespace SolanaAccountsBatchSolanaRequest {
    export const Confirmation = {
        Processed: "processed",
        Confirmed: "confirmed",
        Finalized: "finalized",
    } as const;
    export type Confirmation = (typeof Confirmation)[keyof typeof Confirmation];
}
