// This file was auto-generated by Fern from our API Definition.

import { EthereumClient } from "./api/resources/ethereum/client/Client.js";
import { EthereumSepoliaClient } from "./api/resources/ethereumSepolia/client/Client.js";
import { SolanaClient } from "./api/resources/solana/client/Client.js";
import { SolanaDevnetClient } from "./api/resources/solanaDevnet/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace Mainly {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Mainly {
    protected readonly _options: NormalizedClientOptionsWithAuth<Mainly.Options>;
    protected _ethereum: EthereumClient | undefined;
    protected _ethereumSepolia: EthereumSepoliaClient | undefined;
    protected _solana: SolanaClient | undefined;
    protected _solanaDevnet: SolanaDevnetClient | undefined;

    constructor(options: Mainly.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get ethereum(): EthereumClient {
        return (this._ethereum ??= new EthereumClient(this._options));
    }

    public get ethereumSepolia(): EthereumSepoliaClient {
        return (this._ethereumSepolia ??= new EthereumSepoliaClient(this._options));
    }

    public get solana(): SolanaClient {
        return (this._solana ??= new SolanaClient(this._options));
    }

    public get solanaDevnet(): SolanaDevnetClient {
        return (this._solanaDevnet ??= new SolanaDevnetClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
