// This file was auto-generated by Fern from our API Definition.

export const MainlyEnvironment = {
    Default: "https://api.mainly.live",
} as const;

export type MainlyEnvironment = typeof MainlyEnvironment.Default;
