// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         addresses: ["addresses"]
 *     }
 */
export interface EthereumAccountsBatchEthereumRequest {
    addresses: string[];
    block?: EthereumAccountsBatchEthereumRequest.Block;
}

export namespace EthereumAccountsBatchEthereumRequest {
    export const Block = {
        Earliest: "earliest",
        Latest: "latest",
        Pending: "pending",
        Safe: "safe",
        Finalized: "finalized",
    } as const;
    export type Block = (typeof Block)[keyof typeof Block];
}
