// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         transaction: {}
 *     }
 */
export interface EthereumNetworkEstimateFeesEthereumRequest {
    transaction: EthereumNetworkEstimateFeesEthereumRequest.Transaction;
}

export namespace EthereumNetworkEstimateFeesEthereumRequest {
    export interface Transaction {
        from?: string | undefined;
        to?: string | undefined;
        value?: string | undefined;
        data?: string | undefined;
        gas?: string | undefined;
        gasPrice?: string | undefined;
        maxFeePerGas?: string | undefined;
        maxPriorityFeePerGas?: string | undefined;
    }
}
