// This file was auto-generated by Fern from our API Definition.

import * as MainlyTypes from "../../../src/api/index";
import { Mainly } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("NetworkClient", () => {
    test("getStatus (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            chain: "ethereum",
            chainId: 1,
            networkId: "networkId",
            blockNumber: 1,
            clientVersion: "clientVersion",
            syncing: true,
        };

        server
            .mockEndpoint()
            .get("/v1/ethereum/network/status")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.ethereum.network.getStatus();
        expect(response).toEqual(rawResponseBody);
    });

    test("getStatus (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum/network/status")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereum.network.getStatus();
        }).rejects.toThrow(MainlyTypes.BadRequestError);
    });

    test("getStatus (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum/network/status")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereum.network.getStatus();
        }).rejects.toThrow(MainlyTypes.UnauthorizedError);
    });

    test("getStatus (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum/network/status")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereum.network.getStatus();
        }).rejects.toThrow(MainlyTypes.NotFoundError);
    });

    test("getStatus (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum/network/status")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereum.network.getStatus();
        }).rejects.toThrow(MainlyTypes.ConflictError);
    });

    test("getStatus (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum/network/status")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereum.network.getStatus();
        }).rejects.toThrow(MainlyTypes.UnprocessableEntityError);
    });

    test("getStatus (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum/network/status")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereum.network.getStatus();
        }).rejects.toThrow(MainlyTypes.TooManyRequestsError);
    });

    test("getStatus (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum/network/status")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereum.network.getStatus();
        }).rejects.toThrow(MainlyTypes.InternalServerError);
    });

    test("getStatus (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum/network/status")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereum.network.getStatus();
        }).rejects.toThrow(MainlyTypes.ServiceUnavailableError);
    });

    test("getFees (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            gasPrice: { wei: "wei", gwei: "gwei" },
            baseFee: { wei: "wei", gwei: "gwei" },
            priorityFee: {
                low: { wei: "wei", gwei: "gwei" },
                medium: { wei: "wei", gwei: "gwei" },
                high: { wei: "wei", gwei: "gwei" },
            },
        };

        server
            .mockEndpoint()
            .get("/v1/ethereum/network/fees")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.ethereum.network.getFees();
        expect(response).toEqual(rawResponseBody);
    });

    test("getFees (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum/network/fees")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereum.network.getFees();
        }).rejects.toThrow(MainlyTypes.BadRequestError);
    });

    test("getFees (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum/network/fees")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereum.network.getFees();
        }).rejects.toThrow(MainlyTypes.UnauthorizedError);
    });

    test("getFees (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum/network/fees")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereum.network.getFees();
        }).rejects.toThrow(MainlyTypes.NotFoundError);
    });

    test("getFees (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum/network/fees")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereum.network.getFees();
        }).rejects.toThrow(MainlyTypes.ConflictError);
    });

    test("getFees (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum/network/fees")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereum.network.getFees();
        }).rejects.toThrow(MainlyTypes.UnprocessableEntityError);
    });

    test("getFees (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum/network/fees")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereum.network.getFees();
        }).rejects.toThrow(MainlyTypes.TooManyRequestsError);
    });

    test("getFees (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum/network/fees")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereum.network.getFees();
        }).rejects.toThrow(MainlyTypes.InternalServerError);
    });

    test("getFees (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum/network/fees")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereum.network.getFees();
        }).rejects.toThrow(MainlyTypes.ServiceUnavailableError);
    });

    test("estimateFees (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: {} };
        const rawResponseBody = { gasLimit: "gasLimit", gasLimitHex: "gasLimitHex" };

        server
            .mockEndpoint()
            .post("/v1/ethereum/network/fees/estimate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.ethereum.network.estimateFees({
            transaction: {},
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("estimateFees (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: {} };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/ethereum/network/fees/estimate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereum.network.estimateFees({
                transaction: {},
            });
        }).rejects.toThrow(MainlyTypes.BadRequestError);
    });

    test("estimateFees (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: {} };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/ethereum/network/fees/estimate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereum.network.estimateFees({
                transaction: {},
            });
        }).rejects.toThrow(MainlyTypes.UnauthorizedError);
    });

    test("estimateFees (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: {} };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/ethereum/network/fees/estimate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereum.network.estimateFees({
                transaction: {},
            });
        }).rejects.toThrow(MainlyTypes.NotFoundError);
    });

    test("estimateFees (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: {} };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/ethereum/network/fees/estimate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereum.network.estimateFees({
                transaction: {},
            });
        }).rejects.toThrow(MainlyTypes.ConflictError);
    });

    test("estimateFees (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: {} };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/ethereum/network/fees/estimate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereum.network.estimateFees({
                transaction: {},
            });
        }).rejects.toThrow(MainlyTypes.UnprocessableEntityError);
    });

    test("estimateFees (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: {} };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/ethereum/network/fees/estimate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereum.network.estimateFees({
                transaction: {},
            });
        }).rejects.toThrow(MainlyTypes.TooManyRequestsError);
    });

    test("estimateFees (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: {} };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/ethereum/network/fees/estimate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereum.network.estimateFees({
                transaction: {},
            });
        }).rejects.toThrow(MainlyTypes.InternalServerError);
    });

    test("estimateFees (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { transaction: {} };
        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .post("/v1/ethereum/network/fees/estimate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereum.network.estimateFees({
                transaction: {},
            });
        }).rejects.toThrow(MainlyTypes.ServiceUnavailableError);
    });
});
