// This file was auto-generated by Fern from our API Definition.

import * as MainlyTypes from "../../../src/api/index";
import { Mainly } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("WalletsClient", () => {
    test("getBalance (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { address: "address", wei: "wei", eth: "eth" };

        server
            .mockEndpoint()
            .get("/v1/ethereum/wallets/address/balance")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.ethereum.wallets.getBalance({
            address: "address",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getBalance (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum/wallets/address/balance")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereum.wallets.getBalance({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.BadRequestError);
    });

    test("getBalance (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum/wallets/address/balance")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereum.wallets.getBalance({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.UnauthorizedError);
    });

    test("getBalance (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum/wallets/address/balance")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereum.wallets.getBalance({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.NotFoundError);
    });

    test("getBalance (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum/wallets/address/balance")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereum.wallets.getBalance({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.ConflictError);
    });

    test("getBalance (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum/wallets/address/balance")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereum.wallets.getBalance({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.UnprocessableEntityError);
    });

    test("getBalance (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum/wallets/address/balance")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereum.wallets.getBalance({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.TooManyRequestsError);
    });

    test("getBalance (8)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum/wallets/address/balance")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereum.wallets.getBalance({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.InternalServerError);
    });

    test("getBalance (9)", async () => {
        const server = mockServerPool.createServer();
        const client = new Mainly({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server
            .mockEndpoint()
            .get("/v1/ethereum/wallets/address/balance")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.ethereum.wallets.getBalance({
                address: "address",
            });
        }).rejects.toThrow(MainlyTypes.ServiceUnavailableError);
    });
});
