// This file was auto-generated by Fern from our API Definition.

export interface SolanaNetworkGetBlockhashSolanaResponse {
    blockhash: string;
    lastValidBlockHeight: number;
    expiresInSeconds: number;
}
