// This file was auto-generated by Fern from our API Definition.

export interface EthereumTokensGetEthereumSepoliaResponse {
    contract: string;
    standard: EthereumTokensGetEthereumSepoliaResponse.Standard;
    name: string | null;
    symbol: string | null;
    decimals: number;
    supply: EthereumTokensGetEthereumSepoliaResponse.Supply;
    price: number | null;
    logo: string | null;
}

export namespace EthereumTokensGetEthereumSepoliaResponse {
    export const Standard = {
        Erc20: "erc-20",
    } as const;
    export type Standard = (typeof Standard)[keyof typeof Standard];

    export interface Supply {
        raw: string;
        ui: string;
    }
}
